### ISSUE TITLE
Roadmap MVP

### ISSUE THREAD

**Issue by JohannesNakayama** [social-protocols/Y#3]
### Required Features for MVP

**Notes**

- [x] find top note for any given post

The top note of a post should be the reply to that post that most likely changes users' minds wrt the post without the note.

**Hashtags**

- [ ] implement hashtags

Hashtags are convenient to structure broader conversations and to label content wrt those broader conversations.

Some ideas on what hashtags could be used for:

- as entities to subscribe to: users could subscribe to hashtags and get posts with that hashtag into their feeds
- as channels to post to: users could post to hashtags in order to narrow the scope of the conversation they're entering
- as frontpages: a hashtag could loosely define a community that has a frontpage with conversations with that hashtag
- voting on hashtags: hashtags could be added as context by users other than the post author -> give users the ability to help structuring the conversations (example: a #python community around the programming language, then someone posts something about a python snake which the users of the #python community could then relabel #python-snake)

**Ranking**

- [ ] an algorithm to weight posts against one another

Based on the metaphor of collective cognitive dissonance: If context (a reply) exists for a post that changes our beliefs about the likelihood that people vote in a certain way for this post, we think of the network to be in a state of "cognitive dissonance". The ranking algorithm should aim to resolve cognitive dissonance.

**Feed**

- [ ] generate (personalized?) streams of posts for users

This will be the feed users get on their personal frontpage. We should consider some scheme to discourage doom scrolling.

Some ideas on what could make it into a user's stream:

- posts with hashtags users subscribed to
- posts related to conversations users participated in
- new information (i.e., notes) on posts users voted on (the ranking algorithm optimizes for changing minds -> needs to direct attention to new contextual information if users voted before)

**Agent Simulation**

- [ ] create a GPT agent simulation that gives us a sense of whether the concept works

Before we launch and test the concept with real users, we should have a general feel of whether the concept works or not. This is the goal of the GPT agent simulation.

**Outreach**

- [x] landing page
- [x] newsletter (with sign up option on landing page)

Something to give people we talk to about the project to stay up-to-date and sign up for the launch. Doesn't need to be shiny, just something we can send to people and that they can potentially send to other people.
